Create client.sls
tcpcloud/salt-formula-nfs pull request #1
Opened 2017-06-08 14:43 UTC by mitroko

It is dangerous to use {{ mount.path }} as a resource id as it may duplicate defined one.

Example:
Detected conflicting IDs, SLS IDs need to be globally unique.
The conflicting ID is '/var/lib/glance/images' and is found in SLS 'base:glance.server' and SLS 'base:nfs.client'

This patch fixes that issue.

2017-06-08 14:43 UTC, cloudlab-autobuild commented
Can one of the admins verify this patch?

2017-06-08 15:18 UTC, cznewt requested changes

2017-06-08 15:18 UTC, cznewt commented on nfs/client.sls
> +{{ mount.path|replace("/","_") }}_mount:
better prefix it nfs_mount_ please

2017-06-08 15:27 UTC, mitroko commented
Done

2017-09-19 09:06 UTC, cznewt approved these changes

2017-09-19 09:06 UTC, merged